#ifndef __OPERATOR_ENUM_H__

#if OPERATOR_TYPE_ENUM_STRING
	#undef OPERATOR_TYPE_ENUM_STRING
	#include "operator_enum.h"
	#define OPERATOR_TYPE_ENUM_STRING 1
	
	#define REGISTER_OPERATOR_TYPE(X) #X
#else
	#define REGISTER_OPERATOR_TYPE(X) X
#endif

#if OPERATOR_TYPE_ENUM_STRING
	static const char* OPERATOR_TYPE_STRINGS[] = {
#else
	enum OPERATOR_TYPE {
#endif

		REGISTER_OPERATOR_TYPE( OP_TYPE_NONE ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_INC ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_DEC ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_INC_POST ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_DEC_POST ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_LB ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_RB ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_DOT ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_INC_PRE ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_DEC_PRE ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_UPLUS ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_UMINUS ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_NOT ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_BW_NOT ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_MULT ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_DIV ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_MOD ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_ADD ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_SUB ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_LSHIFT ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_RSHIFT ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_LT ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_LE ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_GT ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_GE ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_EQ ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_NEQ ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_BW_AND ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_BW_XOR ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_BW_OR ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_AND ),

		REGISTER_OPERATOR_TYPE( OP_TYPE_CMP_OR ),
		//ternary 

		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN_ADD ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN_SUB ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN_MULT ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN_DIV ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN_BW_AND ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN_BW_XOR ),
		REGISTER_OPERATOR_TYPE( OP_TYPE_ASSIGN_BW_OR )
		};

	#undef REGISTER_OPERATOR_TYPE

const char* OPERATOR_TYPE_STRING(OPERATOR_TYPE type);

#define __OPERATOR_ENUM_H__
#endif