#pragma once

namespace maps {
	static const char * sp[] = {
		"cuba",
		"vorkuta",
		"pentagon",
		"flashpoint",
		"khe_sanh",
		"hue_city",
		"kowloon",
		"fullahead",
		"creek_1",
		"river",
		"wmd_sr71",
		"wmd",
		"pow",
		"rebirth",
		"int_escape",
		"underwaterbase",
	};

	static const char * zm[] = {
		"zombie_theater",
		"zombie_pentagon",
		"zombietron",
		"zombie_cosmodrome",
		"zombie_coast",
		"zombie_temple",
		"zombie_moon",
		"zombie_cod5_asylum",
		"zombie_cod5_factory",
		"zombie_cod5_prototype",
		"zombie_cod5_sumpf",
	};

	static const char * mp[] = {
		"mp_area51",
		"mp_array",
		"mp_berlinwall2",
		"mp_cairo",
		"mp_cosmodrome",
		"mp_cracked",
		"mp_crisis",
		"mp_discovery",
		"mp_drivein",
		"mp_duga",
		"mp_firingrange",
		"mp_golfcourse",
		"mp_gridlock",
		"mp_hanoi",
		"mp_havoc",
		"mp_hotel",
		"mp_kowloon",
		"mp_mountain",
		"mp_nuked",
		"mp_outskirts",
		"mp_radiation",
		"mp_russianbase",
		"mp_silo",
		"mp_stadium",
		"mp_villa",
		"mp_zoo",
	};
}